package QiyewexinTest;// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Cookie;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class TestwexinTest {

  public static String url = "https://work.weixin.qq.com/";
  @Test
  public void testStart(){
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\liky1\\Downloads\\chromedriver\\chromedriver.exe");
    WebDriver driver = new ChromeDriver();
    driver.get(url);
    driver.manage().window().maximize();
    driver.findElement(By.linkText("企业登录")).click();

    driver.manage().addCookie(new Cookie("wwrtx.sid","oBVP3UKSLgcmXYsno7x0bgjrnRNw79XOhh-hobp7zdbyAyQFH8TztxhUpKgQQdQb"));
    driver.navigate().refresh();
//    driver.close();
    System.out.println(driver.manage().getCookies());

  }


}
